export const INSPECT_CARD_TARGET_SCALE = 2.06;
export const INSPECT_CARD_VERTICAL_COMPACT_RATIO = 0.96;
export const INSPECT_CARD_MAX_HEIGHT_RATIO = 0.58;
export const INSPECT_CARD_MAX_WIDTH_RATIO = 0.78;
export const INSPECT_CARD_OVERLAY_ALPHA = 0.2;
export const INSPECT_CARD_OVERLAY_DEPTH = 840;
export const INSPECT_CARD_DEPTH = 850;
export const INSPECT_CARD_TWEEN_IN_MS = 150;
export const INSPECT_CARD_TWEEN_OUT_MS = 95;
export const INSPECT_CARD_STAT_BADGE_SCALE = 1.28;
export const INSPECT_CARD_TYPOGRAPHY_SCALE = 1.1;
export const INSPECT_CARD_BODY_LINE_SPACING = 5;

export const HAND_CARD_STAT_BADGE_SCALE = 1.1;
export const HAND_CARD_TYPOGRAPHY_SCALE = 1.12;
export const HAND_CARD_TITLE_TYPOGRAPHY_SCALE = 1.2;
export const HAND_CARD_BODY_LINE_SPACING = 3;
export const HAND_CARD_LONG_PRESS_MS = 425;
